### ISSUE TITLE
Peers doesn't get added while creating Private and Permissioned network using the IBFT 2.0

### ISSUE THREAD

**Issue by asharoo1** [hyperledger/besu-docs#1014]
I'm trying to Create a private network using the IBFT 2.0 following this doc
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

In my local machine, I'm running this command to start Node-2:
`besu --data-path=data --genesis-file=../genesis.json --bootnodes=<Node-1 Enode URL> --p2p-port=30304 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8546`

And then I can see that it works fine and i can see the peer count as 2

But when I'm trying to start the same Node-2 using docker with this command:
`docker run -it -d -p 8546:8546 -p 30304:30304 --mount type=bind,source=/home/ubuntu/IBFT-Network/Node2/data,target=/datapth --mount type=bind,source=/home/ubuntu/IBFT-Network,target=/genesispath --name node2 hyperledger/besu:latest --genesis-file=/genesispath/genesis.json --data-path=/datapth --rpc-http-port=8546 --p2p-port=30304 --bootnodes=enode://xyz_xyz@127.0.0.1:30303 --rpc-http-api=ETH,NET,IBFT --rpc-http-enabled --host-allowlist="*" --rpc-http-cors-origins="all"`

Then the node starts fine but it does not get connected to the bootnode, as peer count remains 0. The peers doesn't get added.

Same is the case when adding peers to Permissioned Network

Can someone please check these, Any help would be appreciated, thanks

**Comment by alexandratran** [comment]
From @macfarla:
> I think the issue with this is you can't use the loopback address 127.0.0.1 with docker. You need to use the effective IP of the docker container. The quickstart does this by specifying an IP address for each node, and then use that IP address for the bootnode enode. https://github.com/ConsenSys/quorum-dev-quickstart/blob/master/templates/besu/docker-compose.yml

**Comment by alexandratran** [comment]
Another comment from @Ezzahhh:
> Yep docker’s default networking is bridge so 127.0.0.1 in a container will refer internally in the container and not the host. They could still run it in the container and use 127.0.0.1 if they add the --network="host" flag to the docker run command. Though then they need to be sure there are no overlapping ports as any internal container ports will then be accessible on the host. Since that is the case, setting networking to host for the container means -p commands will be ignored by docker and produce a warning.

> It should be noted that if they’re running on Windows with WSL, setting network to host will not function the same as Linux; this is to do with internal networking WSL does. In that case, it would be best to follow the quickstart and run everything in docker

Let me know if this fixes your issue @asharoo1!
