### ISSUE TITLE
Confirm whether an inactive validator's `lastproposedblocknumber` is 0

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1021]
The consensus docs say that:

> An inactive validator's `lastProposedBlockNumber` is `0x0`.

Confirm the following question from @NicolasMassart in https://github.com/hyperledger/besu-docs/pull/1013:

> Are you sure of this one?
> if the validator became inactive after validating some blocks, it may be more than zero. [Code comment says](https://github.com/hyperledger/besu/blob/6f8b7a5de44388c8442b80ffe0dc0d8357f6da06/consensus/common/src/main/java/org/hyperledger/besu/consensus/common/jsonrpc/AbstractGetSignerMetricsMethod.java#L85) "the block number of the last block proposed by each validator".
> However depending on how long the signer has been inactive, the lastProposedBlockNumber may be far from head or not. On any case, if you have a validator with a last bloc older than the ones created in the last round, it means the validator have not been active in the last round.
> Consider this comment as just a "check needed" one, don't take it as truth, I may have missed something here.

**Comment by siladu** [comment]
I ran a test with QBFT. Assuming "inactive validator" means the validator is offline, then @NicolasMassart is correct, then it returns its actual lastProposedBlockNumber, not 0x0. For example, I started a network of 4 validators, produced some blocks, then stopped the first one while letting the other 3 continue...
`qbft_getSignerMetrics` returned:
```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": [
        {
            "address": "0xc766f21655e24763f6e70153c27e496cd8cb6fd3",
            "proposedBlockCount": "0x8",
            "lastProposedBlockNumber": "0x1f"
        },
        {
            "address": "0x5aa93f3295c0eb1341d1bf02889504adfc5c5868",
            "proposedBlockCount": "0xe",
            "lastProposedBlockNumber": "0x30"
        },
        {
            "address": "0x25261caa25205c4db5e3f4757d655570066f6d5b",
            "proposedBlockCount": "0xe",
            "lastProposedBlockNumber": "0x32"
        },
        {
            "address": "0xab3234975f99f1d5a1857ce1f9cdf1c46a8dde45",
            "proposedBlockCount": "0xe",
            "lastProposedBlockNumber": "0x31"
        }
    ]
}
```

I assume IBFT works exactly the same. 
Clique, I'm not sure, but it does appear to use the same code (that Nico linked to)

It would be interesting to understand where this came from before we change anything. Probably it's how it used to work, so I would be able to see that in the code history. I may also double check with @jframe when they're back next week just in case.

**Comment by siladu** [comment]
I also tested the scenario when the validator is voted out by the others (and removed from the validator list). No difference in this scenario: lastProposedBlockNumber was still `0x1f` for a block range inclusive of that validator.

**Comment by siladu** [comment]
OK so looking at the history, this commit by @matkt: https://github.com/hyperledger/besu/pull/343
was followed up by the docs tip in question: https://github.com/hyperledger/besu-docs/issues/147

So it looks like "inactive validators" really means validator/signers who were _yet_ to sign a block ("never active"), rather than had previously signed. 

I'm not sure how useful that tip is then. It's current wording is misleading...can anyone see a good reason to reword rather than remove this @alexandratran @NicolasMassart?

**Comment by alexandratran** [comment]
Thanks for confirming this @siladu! I think it makes sense to just remove the tip.
