### ISSUE TITLE
Updated Helm content and links

### ISSUE THREAD

**Issue by rolandtyler** [hyperledger/besu-docs#1027]
The `dev` and `prod` folders were merged into one `helm` folder for [quorum-kubernetes](https://github.com/ConsenSys/quorum-kubernetes/tree/master/helm). Update [this page](https://besu.hyperledger.org/en/latest/Tutorials/Kubernetes/Overview/) with new links and remove reference to `dev` and `prod`.

**Comment by NicolasMassart** [comment]
See https://github.com/ConsenSys/quorum-kubernetes/commit/b43675f5d31c865b3800a302f1b4c76f396b1911 for the commit that changed all the paths
