### ISSUE TITLE
Remove clique from docs

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1034]
* remove https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/
* remove tutorials https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-Private-Clique-Network/
* remove https://besu.hyperledger.org/en/stable/HowTo/Configure/Consensus-Protocols/Clique/#migrate-from-clique-to-another-consensus-protocol 
* change permissioning tutorial from Clique to IBFT2 https://besu.hyperledger.org/en/stable/Tutorials/Permissioning/Create-Permissioned-Network/
* Also mentioned here https://besu.hyperledger.org/en/stable/Concepts/Consensus-Protocols/Comparing-PoA/

- [ ] Missing content
- [x] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## Change suggestion

Change any tutorials to use QBFT/IBFT2

**Comment by rolandtyler** [comment]
Closing per comment on EEA requirement on #1037
