### ISSUE TITLE
CORS remix example mixes up list syntax between CLI param and config file

### ISSUE THREAD

**Issue by garyschulte** [hyperledger/besu-docs#1050]
## Describe the bug
The note section in [rpc-http-cors-origins](https://github.com/hyperledger/besu-docs/blob/main/docs/Reference/CLI/CLI-Syntax.md?plain=1#L2935) is using a CLI parameter option, `--rpc-http-cors-origins` but it is supplying a value that is a config file list format.

e.g. `--rpc-http-cors-origins=["chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn", "http://remix.ethereum.org"]` 

should be either:
`rpc-http-cors-origins=["chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn", "http://remix.ethereum.org"]`
or:
`--rpc-http-cors-origins="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn","http://remix.ethereum.org"`

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [X] Confusing or misleading content
- [ ] Other

**Comment by poupas** [comment]
Thank you for addressing this.

Please note that the origin must not be specified between double quotes.

For example, `--rpc-http-cors-origins=chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn` works, but `--rpc-http-cors-origins="chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn"` does not.
