### ISSUE TITLE
Update: Run Besu and Teku on the Merge testnet page

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu-docs#1114]
## Describe the bug

The page [Run Besu and Teku on the Merge testnet page](https://besu.hyperledger.org/en/stable/Tutorials/Merge-Testnet/) contains outdated parameters for Besu. Some parameters are not used any more others have been renamed.

- [ ] Missing content
- [x] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

**Comment by alexandratran** [comment]
@rolandtyler can you look into this and make sure your PR #1108 uses the correct parameters?

**Comment by rolandtyler** [comment]
Closed to #1108
