### ISSUE TITLE
Annoying blinking effect when loading pages in dark mode

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#1190]
Annoying blinking effect when loading pages in dark mode that makes a white background appear in a flash before the actual dark background.

**Comment by macfarla** [comment]
yes I have noticed this too!

**Comment by Tweaker177** [comment]
I think this is more of a GitHub / iOS issue than a hyperledger besu problem.  I’ve mainly only noticed it when viewing dynamic images/ ones that have both a light mode and dark mode version saved as one file.
