### ISSUE TITLE
Add additional syncing information

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1211]
### Describe the issue

It would be helpful to have more specific information about syncing: total sync times (world state + blockchain download) and disk size estimates for all three networks (Mainnet, goerli, and sepolia). We need to ask the Besu team for these numbers.

See @siladu's comments on https://github.com/hyperledger/besu-docs/pull/1208.

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/get-started/connect/sync-node/

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by MadelineMurray** [comment]
Following up with the engineering team.
