### ISSUE TITLE
[Content] search preview for 'Use OpenTelemetry' page displays the whole page

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1243]
### Describe the issue

I searched for 'batch' and the results in most cases show the first few lines but for the OpenTelemetry page, the whole page is displayed 

### What page has the issue?

https://besu.hyperledger.org/en/stable/private-networks/how-to/monitor/opentelemetry/?h=batc#setting-up-and-running-opentelemetry-with-besu

### Issue type

Missing content

### Change suggestion

![Screenshot 2023-01-11 at 9 46 30 am](https://user-images.githubusercontent.com/2627919/211686119-d9f8a334-1a83-47a2-be92-eff17de2a071.png)

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by alexandratran** [comment]
This doesn't seem to be an issue in the new Docusaurus site.
