### ISSUE TITLE
Snap sync is now the default for named networks

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#1245]
See:
- https://github.com/hyperledger/besu/pull/4204
- https://github.com/hyperledger/besu/issues/4203

Confirm that the related issue has been merged before working on this.

**Comment by MadelineMurray** [comment]
The PR to make snap sync the default was closed without merging.  Have asked how likely this change is to happen in the near future.

**Comment by MadelineMurray** [comment]
This is currently planned for Q1.  Parking for now.

**Comment by macfarla** [comment]
fixed in https://github.com/hyperledger/besu-docs/pull/1515
