### ISSUE TITLE
Document `--rpc-max-batch-size`

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1258]
### Describe the issue

Document new CLI option `--rpc-max-batch-size`. See https://github.com/hyperledger/besu/pull/4965.

### What page has the issue?

CLI options reference

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by siladu** [comment]
Looks like the option is actually named --rpc-http-max-batch-size

**Comment by Gabriel-Trintinalia** [comment]
Default has been changed to 1000: https://github.com/hyperledger/besu/pull/5105

**Comment by bgravenorst** [comment]
Appears to have been bumped to 1024: https://github.com/hyperledger/besu/pull/5108
