### ISSUE TITLE
Document `debug_getRawBlock` and `debug_getRawHeader`

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1259]
### Describe the issue

Document new RPC `debug` methods `debug_getRawBlock` and `debug_getRawHeader`. See https://github.com/hyperledger/besu/pull/5011.

### What page has the issue?

API methods reference

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by bgravenorst** [comment]
Already documented here:
https://besu.hyperledger.org/en/latest/public-networks/reference/api/#debug_getrawblock
https://besu.hyperledger.org/en/latest/public-networks/reference/api/#debug_getrawheader
