### ISSUE TITLE
[Content] Remove link to Postman API

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1286]
### Describe the issue

Remove the reference to the Besu API on Postman, as that documentation hasn't been maintained for two years.

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/reference/api/

### Issue type

Outdated content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by siladu** [comment]
Would be good to understand/discuss the scope of what needs removing.

I think this may still be a valid and useful link for example: https://besu.hyperledger.org/assets/postman/postman_collection.json

The "Run in postman" button still works too.

It's just https://api.besu.hyperledger.org/ with the issue I think.

**Comment by deveshXm** [comment]
Hi, I'd like to work on this issue.

**Comment by alexandratran** [comment]
@deveshXm Thanks! I've assigned this to you.

**Comment by deveshXm** [comment]
@alexandratran Have I done some wrong changes? Also I can see of the tests did not pass. What can I do from my side?

**Comment by siladu** [comment]
@alexandratran The issue is that we no longer pay for part of the postman service, so one of the links is getting a 404. However, some of the links still work and they are definitely used because we are in the top 25 most downloaded postman collections! https://www.postman.com/explore/most-popular-apis-this-year

I would like to discuss with @non-fungible-nelson before we pull the trigger on this please, since the PR removes even the working links.

**Comment by non-fungible-nelson** [comment]
Was the postman collection manually maintained by Pliny @alexandratran ? Trying to figure out the overhead

**Comment by alexandratran** [comment]
@non-fungible-nelson yes, it was maintained as an experiment by Nicolas Massart, but he stopped maintaining it at some point and he's no longer with Pliny.

**Comment by non-fungible-nelson** [comment]
We did top the charts for postman collection downloads... curious if we can find a way to automate this somehow... otherwise, should probably take off Pliny's plate

**Comment by siladu** [comment]
cc-ing @garyschulte as he made a comment about how the API is published for teku.

As a side note, I may have a version of the collection including the engine api I'd like to publish, it's not quite ready yet.

**Comment by alexandratran** [comment]
Fixed by #1302
