### ISSUE TITLE
[Content] Document `--ethstats-cacert-file` and update `--ethstats` default

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1297]
### Describe the issue

Document `--ethstats-cacert-file` CLI option and update `--ethstats` default to 443 for wss and 80 for ws. See https://github.com/hyperledger/besu/pull/5301. 

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/#ethstats

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by MysticRyuujin** [comment]
https://github.com/hyperledger/besu/pull/5301#issuecomment-1535469115
