### ISSUE TITLE
[Content] Add note that `min-block-occupancy-ratio` is ignored for PoS

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1344]
### Describe the issue

Add note that the `--min-block-occupancy-ratio` option is ignored for PoS networks. See https://github.com/hyperledger/besu/pull/5491 for more info.

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/#min-block-occupancy-ratio

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by AnmolSirola** [comment]
@alexandratran Can I work on this issue ?

**Comment by alexandratran** [comment]
@AnmolSirola Sure! Assigned it to you.

**Comment by alexandratran** [comment]
fixed by #1354
