### ISSUE TITLE
[Content] Update `ethstats` description to allow optional scheme

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1345]
### Describe the issue

Update the `--ethstats` option description to note that `ws://` or `wss://` can optionally be specified in the URL. See https://github.com/hyperledger/besu/pull/5500 for more info.

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/?h=ethstats#ethstats

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by MujahidAli954** [comment]
I want to work on this issue can you assign this to me!

**Comment by alexandratran** [comment]
@MujahidAli954 Assigned to you!

**Comment by alexandratran** [comment]
@MujahidAli954 Please let me know if you're still planning to work on this issue, otherwise I'll assign it to @Bansalayush247!

**Comment by Bansalayush247** [comment]
I am new to open source can you guide what I have to do

**Comment by alexandratran** [comment]
@Bansalayush247 You can follow the contribution guidelines here: https://wiki.hyperledger.org/display/BESU/Documentation+contribution+workflow

Let me know if you have a specific question about the process.

**Comment by Jonnie-Dev** [comment]
Would love to work on this alongside @MujahidAli954 if it's not completed yet
