### ISSUE TITLE
[Content] Update docs for TOML config files

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1347]
### Describe the issue

TOML table headings are now removed when parsing config files. From https://github.com/hyperledger/besu/pull/5483:

> I'd suggest a small update to https://besu.hyperledger.org/en/stable/public-networks/how-to/configuration-file/?h=toml. Perhaps a short paragraph after the existing "Values must conform to TOML specifications..." paragraph that say something along the lines of:
>
> "Table headings are ignored in TOML files. If a valid Besu option is specified under a table heading in a configuration file, Besu will ignore the table heading and read the option in the same way it does for options not under table headings."

### What page has the issue?

https://besu.hyperledger.org/en/stable/public-networks/how-to/configuration-file/?h=toml

### Issue type

Missing content

### Besu documentation issue guidelines

- [X] I read and followed this project's documentation guidelines.

**Comment by AnmolSirola** [comment]
@alexandratran Can I work on this issue ?

**Comment by alexandratran** [comment]
@AnmolSirola Assigned to you! Please make your changes in the `/docs` folder :)

**Comment by Najamulhassan3383** [comment]
Hi @AnmolSirola!
I see you're assigned to the issue. Are you currently working on it? If not, I would like to take it up. Please let me know so that I can start working on it.
Thanks!

**Comment by AnmolSirola** [comment]
@Najamulhassan3383 I am currently working on this issue.

**Comment by alexandratran** [comment]
Fixed by #1355
