### ISSUE TITLE
Revert-reason-enabled docs not quite accurate re. `eth_call`

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu-docs#1361]
The docs on the `--revert-reason-enabled` say that this option is required in order to include the revert reason in "transaction receipt, eth_estimateGas, error, eth_call error, and trace response in Hyperledger Besu."

I think this changed at some point as `eth_estimateGas` and `eth_call` both return the revert reason as a `data` field in the response, without `--revert-reason-enabled` set on the node. Here's an example request & response:

```
{
    "jsonrpc":"2.0",
    "method":"eth_estimateGas",
    "params":[{"from": "0x438df7EA6C26e356A05902Ca7D3831D530f7C7bE", "to": "0x438df7EA6C26e356A05902Ca7D3831D530f7C7bE", "data":"0xa9059cbb000000000000000000000000fdc4e76a273b4033a1ee0c2b73ab45bb9170bf440000000000000000000000000000000000000000000000000000000009999999"}, "latest"],
    "id":1
}
```

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "Execution reverted",
        "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002645524332303a207472616e7366657220616d6f756e7420657863656564732062616c616e63650000000000000000000000000000000000000000000000000000"
    }
}
```

Decoding the `data` field in this example gives you `ERC20: transfer amount exceeds balance`

So I think the `--revert-reason-enabled` option is only applicable to transaction receipts (which I've tested and do indeed only include the revert reason if the flag is turned on) and trace (which I haven't tried but assume still requires the option).

There's also some formatting oddness on the page:

![image](https://github.com/hyperledger/besu-docs/assets/6599269/e035d315-d209-4870-8649-a6ec05d553c3)

**Comment by Blonde488** [comment]
hope you like this!!

**Comment by mjsmike62** [comment]
Can you assign me to this issue?
