### ISSUE TITLE
Update `blockNumber` parameter descriptions

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1385]
For any public API method that contains the `blockNumber` parameter (for example, [`debug_getRawBlock`](https://besu.hyperledger.org/public-networks/reference/api#debug_getrawblock)), update the description to specify that it's a "hexadecimal integer." Also, include `finalized` and `safe` as possible values.

**Comment by mjsmike62** [comment]
@alexandratran, what if a public API method that does not contain `blockNumber` (for example, `newestBlock`), but mentions the string tags minus `finalized` and `safe`. Should this listing of string tags be updated to include the aforementioned tags?

<img width="476" alt="StringTags" src="https://github.com/hyperledger/besu-docs/assets/104706698/bd02392b-48f5-400f-acb7-e8c3e1ad03e0">

**Comment by alexandratran** [comment]
@mjsmike62 yes, go ahead and update any parameter that references the block parameter.
