### ISSUE TITLE
debug_traceTransaction content missing

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1400]
If you look at debug_storageRangeAt
https://besu.hyperledger.org/public-networks/reference/api#debug_storagerangeat
the next item in the list should be debug_traceTransaction
which appears in the list but not in the content of the page

**Comment by alexandratran** [comment]
This is a formatting issue causing `debug_traceTransaction` to show up under the **JSON result** of `debug_storageRangeAt`. @mjsmike62
