### ISSUE TITLE
Document new `tx-pool` options

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1401]
Document:

- `--tx-pool`
- `--layered-tx-pool-layer-max-capacity`
- `--layered-tx-pool-max-prioritized`
- `--layered-tx-pool-max-future-by-sender`

See https://github.com/hyperledger/besu/pull/5772 for context.

**Comment by fab-10** [comment]
See also https://github.com/hyperledger/besu/blob/release-23.10.x/CHANGELOG.md#configuring-the-layered-transaction-pool

FYI: @non-fungible-nelson
