### ISSUE TITLE
broken links to "private network" API methods

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1403]
links from private network pages to particular API methods are going to the public-network page where some of them don't exist

example here but there's probably others
eg
https://besu.hyperledger.org/private-networks/tutorials/privacy/quickstart#deploy-the-private-contract-and-interact-with-the-nodes
links to 
https://besu.hyperledger.org/public-networks/reference/api#eea_sendrawtransaction
which is only found here
https://besu.hyperledger.org/private-networks/reference/api#eea_sendrawtransaction

**Comment by MadelineMurray** [comment]
@bgravenorst - could you assign this one to me please
