### ISSUE TITLE
Document new JVM options

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1415]
Document new JVM options:

- `-XX:G1ConcRefinementThreads`
- `-XX:G1HeapWastePercent`
- `-XX:MaxGCPauseMillis`

Perhaps add a section to [this page](https://besu.hyperledger.org/development/public-networks/how-to/configure-jvm/manage-memory). See https://github.com/hyperledger/besu/pull/5879 for more info.

**Comment by MadelineMurray** [comment]
@bgravenorst - I can't assign this to myself (I'm guessing I may no longer be a docs maintainer). Could you assign to me please.
