### ISSUE TITLE
Document debug_traceCall

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1417]
Document debug_traceCall. See https://github.com/hyperledger/besu/pull/5885 for more info, wait till the PR is merged.

**Comment by ATREAY** [comment]
hey @alexandratran, can I work on this issue if it is available?

**Comment by alexandratran** [comment]
@ATREAY assigned to you!

**Comment by ATREAY** [comment]
Hey @alexandratran, could you please provide specific details regarding the page and location where the content should be added?

**Comment by alexandratran** [comment]
You can add it to the API reference, at the end of the [debug section](https://besu.hyperledger.org/development/public-networks/reference/api#debug-methods).

**Comment by ATREAY** [comment]
Hey @alexandratran, I've included details about the debug_traceCall method. Please check it out when you have a moment.
