### ISSUE TITLE
Document the JSON-RPC methods: `miner_setMinPriorityFee` and `miner_getMinPriorityFee`

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1434]
Document the new JSON-RPC methods: `miner_setMinPriorityFee` and `miner_getMinPriorityFee`.

See PR: [Implement miner_setMinPriorityFee and miner_getMinPriorityFee #6080](https://github.com/hyperledger/besu/pull/6080) for details.

**Comment by MadelineMurray** [comment]
@bgravenorst - could you assign this one to me please
