### ISSUE TITLE
Doc the parameter violations for the JSON-RPC method `miner_setMinPriorityFee`: invalid parameter and missing parameter

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1435]
Document the parameter violations for the new JSON-RPC method `miner_setMinPriorityFee`: invalid parameter and missing parameter. Invalid parameter could be one that's too large (>32 bytes).

See PR: [`setMinPriorityFee` - Return Invalid Param when invalid and use hexadecimal instead of Long #6099](https://github.com/hyperledger/besu/pull/6099) for details. [Document the JSON-RPC methods: `miner_setMinPriorityFee` and `miner_getMinPriorityFee`](https://github.com/hyperledger/besu-docs/issues/1434) is related to this issue.

**Comment by MadelineMurray** [comment]
@bgravenorst - can you assign this one to me please
