### ISSUE TITLE
Document the Clique option to not create empty blocks

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1436]
In the [Genesis file](https://besu.hyperledger.org/development/private-networks/how-to/configure/consensus/clique) topic, document the new Clique option, `createemptyblocks`, to prevent the creation of empty blocks.

See PR: [Add option to clique to skip creating empty blocks #6082](https://github.com/hyperledger/besu/pull/6082) for details.

**Comment by MadelineMurray** [comment]
@bgravenorst - could you assign this one to me please
