### ISSUE TITLE
Document that `input` and `data` fields are acceptable for the payload of transaction-related RPC methods

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1437]
Document that `input` and `data` fields are acceptable for the payload of transaction-related RPC methods. Update the [Transaction call object](https://besu.hyperledger.org/public-networks/reference/api/objects#transaction-call-object) topic with this information.

See PR: [RPC Parameters to accept input and data field #6094](https://github.com/hyperledger/besu/pull/6094).

**Comment by MadelineMurray** [comment]
@bgravenorst - could you assign this one to me please
