### ISSUE TITLE
Document the JSON-RPC methods: `miner_getMinGasPrice` and `miner_setMinGasPrice` for the `min-gas-price` CLI option

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1438]
Document the new JSON-RPC methods: `miner_getMinGasPrice` and `miner_setMinGasPrice` for the `min-gas-price` CLI option [topic](https://besu.hyperledger.org/public-networks/reference/cli/options#min-gas-price).

See PR: [Add API to set and get the minGasPrice at runtime #6097](https://github.com/hyperledger/besu/pull/6097) for details.

**Comment by MadelineMurray** [comment]
Added these when addressing #1434 - this can be closed @bgravenorst

**Comment by fab-10** [comment]
I do not see the documentation for these 2 methods in the current version
