### ISSUE TITLE
bootnodes vs static nodes - add to explanation

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1461]
https://besu.hyperledger.org/development/public-networks/how-to/connect/static-nodes

Suggest to expand the note on this page to highlight the important difference between bootnodes and static nodes -

Static nodes and bootnodes are only treated the same at startup (ie besu tries to connect to them all). However only static nodes (and enodes added via admin_addPeer) are included in "maintained peers" (to which besu regularly attempts to reconnect), not bootnodes. So if you only have bootnodes, after startup you're relying solely on discovery. So in small node networks, we would recommend static nodes (or both) to mitigate low peer count issues.

**Comment by MadelineMurray** [comment]
@bgravenorst - can you assign this one to me please
