### ISSUE TITLE
Document how to prevent accidental downgrade of Besu

### ISSUE THREAD

**Issue by mjsmike62** [hyperledger/besu-docs#1475]
Document how to prevent accidental downgrade of Besu, which can permanently corrupt the database. Also, document the validation process to ensure the preventative steps are effective.

See PR: [Restrict downgrade](https://github.com/hyperledger/besu/pull/6307)

**Note:** Originating PR is not yet merged. Ensure this PR is merged before publishing doc update.

**Comment by non-fungible-nelson** [comment]
Bumping back up as this is will be shipped. @joaniefromtheblock @alexandratran for viz
