### ISSUE TITLE
Documentation label issue

### ISSUE THREAD

**Issue by RohitGupta027** [hyperledger/besu-docs#148]
Correct the spelling error on markdown YAML file (mkdocs.yml) at line no. 160 from Vadidating to Validating. 
<img width="754" alt="Screenshot 2020-02-07 at 15 59 10" src="https://user-images.githubusercontent.com/19914952/74039832-d557b700-49c2-11ea-99af-5180a53969c3.png">

**Comment by MadelineMurray** [comment]
I've fixed this now - thanks for taking the time to raise :-)
