### ISSUE TITLE
metrics page looks extra dangerous

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1494]
https://besu.hyperledger.org/public-networks/how-to/monitor/metrics#monitor-node-performance-using-prometheus

there's a numbered list 1, 2 and then a "Danger" note and then 3 and 4 (and the rest of the page) is all appearing still within the red danger section
![Screenshot 2024-01-31 at 3 11 37 pm](https://github.com/hyperledger/besu-docs/assets/2627919/71963e2e-5502-4ebd-a44b-9788bdee0c7b)

**Comment by dicethedev** [comment]
@alexandratran so the danger should be removed from the page right?

**Comment by alexandratran** [comment]
@dicethedev This is actually a formatting issue that is slightly complex, so I ended up removing the "good first issue label" and addressed it in this PR: #1497.

**Comment by macfarla** [comment]
just created another issue for this same page, might be easy to fix both at same time https://github.com/hyperledger/besu-docs/issues/1499
