### ISSUE TITLE
Deprecate the `--Xp2p-peer-lower-bound` 

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#1506]
For more information see: https://github.com/hyperledger/besu/pull/6501

**Comment by joaniefromtheblock** [comment]
Chatted with @macfarla about this. This was an early access feature and is now no longer available. There is no alternative or replacement for this option. There is only the upper bound (max). Should this be removed entirely?? 

The deprecation is documented in the [changelog](https://github.com/hyperledger/besu/blob/main/CHANGELOG.md), so is this need in our docs?
