### ISSUE TITLE
Document `eth_blobBaseFee`

### ISSUE THREAD

**Issue by alexandratran** [hyperledger/besu-docs#1521]
Document `eth_blobBaseFee` RPC method. See https://github.com/hyperledger/besu/pull/6581 source code for details.

**Comment by bgravenorst** [comment]
I think this may require additional conceptual content (In Concepts -> Transactions) that can be leveraged from Teku. Also, there appear to be updates to `eth_feeHistory` to now include Blob gas in it's returned results.
