### ISSUE TITLE
migrate remaining docs from besu repo

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1529]
There are a couple of md files still in besu repo - surfaced by this PR https://github.com/hyperledger/besu/pull/6683

There's a [privacy migration feature](https://github.com/hyperledger/besu/blob/main/docs/Private-Txns-Migration.md)

I'm surprised to find these docs even still here. But - I can't see the equivalent docs in the [besu private network docs ](https://besu.hyperledger.org/private-networks/reference/cli/options)

Note the docs reference besu version 1.4 which is very old - but this feature still exists in current besu.

And some pretty technical docs on how to run tracing - idk if we want to move this or not https://github.com/hyperledger/besu/tree/main/docs/tracing

**Comment by alexandratran** [comment]
We have similar tracing docs in the current docs, and it's unlikely that users will use the privacy migration feature with more recent versions of Besu. Closing for now.
