### ISSUE TITLE
Add page summarising what mixhash, coinbase, and chainid specify 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#154]
User feedback: 
IMO there should be a dedicated page on this, as this is a crucial step. There should be documentation on what 'mixhash', 'coinbase', 'chainid' specify on a dedicated page
- An Index of currently used ChainID's is a must

**Comment by timbeiko** [comment]
@MadelineMurray we already have details on `coinbase`([here](https://besu.hyperledger.org/en/stable/Reference/Config-Items/#genesis-block-parameters)) and `chainID` ([here](https://besu.hyperledger.org/en/stable/Concepts/NetworkID-And-ChainID/)), including a table with the various chain IDs. 

<img width="570" alt="Screen Shot 2020-08-14 at 12 50 36 PM" src="https://user-images.githubusercontent.com/9390255/90287450-c6980400-de2c-11ea-9d8e-a421c53d66bb.png">


The only thing missing would be `mixhash` and it is used to store an intermediate value in the PoW calculation. I'm not sure it is worth providing a long explanation for it, but we could if we feel that is valuable. This [SO post](https://ethereum.stackexchange.com/questions/5833/why-do-we-need-both-nonce-and-mixhash-values-in-a-block) gives a good overview: 

> mixhash is actually calculated from nonce as intermediate value when validating PoW with Hashimoto algorithm. But this calculation is still pretty heavy and a node might be DDoSed by blocks with incorrect nonces. mixhash is included into block to perform lightweight PoW 'pre-validation' to avoid such attack, as generating a correct mixhash still requires at least some work for attacker
