### ISSUE TITLE
Tutorial content need to update

### ISSUE THREAD

**Issue by YooogiYun** [hyperledger/besu-docs#1543]
In the [Quorum Developer Quickstart/public-transactions](https://besu.hyperledger.org/private-networks/tutorials/quickstart#public-transactions) part.

here needs to be updated.

```bash
cd smart_contracts
npm install
node scripts/public/public_tx.js
# or via ethers
node scripts/public/public_tx_ethers.js
```
should update to

```bash
cd smart_contracts
npm install
node scripts/public/hre_1559_public_tx.js
# or via ethers
node scripts/public/hre_public_tx.js
```

![image](https://github.com/hyperledger/besu/assets/127641096/9b118725-9de1-4944-a8a6-b8c23c2fbeda)
![image](https://github.com/hyperledger/besu/assets/127641096/fbe8e50c-6016-42b3-8030-65073d431781)

```bash
...
node scripts/public/eth_tx.js
```
should update to 

```bash
...
node scripts/public/hre_eth_tx.js
```

![image](https://github.com/hyperledger/besu/assets/127641096/f53b9154-68d1-496c-a207-9a87bb15102c)

Thanks

**Comment by joaniefromtheblock** [comment]
Thank you @macfarla and @YooogiYun
