### ISSUE TITLE
No docs for `debug_traceTransaction` API

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu-docs#1556]
The `debug_traceTransaction` call is listed in the API reference docs:

![image](https://github.com/hyperledger/besu-docs/assets/6599269/05d01251-41a5-4f61-b97b-170b1115c427)

However, the link resolves to https://besu.hyperledger.org/public-networks/reference/api#debug_tracetransaction which doesn't appear to exist.

**Comment by alexandratran** [comment]
@matthew1001 That links works for me, taking me to the `debug_traceTransaction` section in the docs: https://besu.hyperledger.org/public-networks/reference/api#debug_tracetransaction

Can you try again or provide more context on how it's failing for you?

**Comment by matthew1001** [comment]
That's interesting. Yes that link works fine for me @alexandratran. I think when I've arrived at the the Besu docs via Google I've ended up at https://besu.hyperledger.org/23.4.0/public-networks/reference/api which must be the link I took the screenshot ^^ from. Happy to close this as the latest version clearly does have it documented.
