### ISSUE TITLE
The `sequenced` transaction pool behaviour isn't documented

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu-docs#1561]
I think the Transaction Pool topic https://besu.hyperledger.org/public-networks/concepts/transactions/pool needs a section on the "Sequenced" transaction pool. I've put together a summary of the changes I think are needed, and some initial text suggestions to describe the behaviour of the pool

1. https://besu.hyperledger.org/public-networks/reference/cli/options#tx-pool
   - I suggest we now remove  the "previously known as legacy" text as it's probably no longer needed.
   - I also think we should change the wording of "to opt out of the layered transaction pool." and just say "to use the sequenced transaction pool."

2. https://besu.hyperledger.org/public-networks/concepts/transactions/pool
   - I think this needs 2 sections. One for layered and one for sequenced, ideally with an initial intro paragraph that explains that there are 2 types of transaction pool available, and that the layered pool is the recommended pool for public chains and the sequenced pool is the recommended pool for private chains. 
   - For the description of the sequenced pool I've put some initial suggested text below

## Sequenced transaction pool

The sequenced transaction pool is recommended for private blockchains. To select the sequenced transaction pool set the `--tx-pool=sequenced` configuration option. If the enterprise configuration profile has been chosen using `--profile=enterprise` the sequenced transaction pool will be used by default.

The sequenced transaction pool is designed to be more suitable to enterprise environments. Its design is oriented around behaviouring like a first-in-first-out (FIFO) queue of transactions and therefore has the following characteristics:

- Transactions are selected in the order they are submitted regardless of which sender submitted the transaction
- When the transaction pool is full newer transactions are evicted first. This reduces the chance of a nonce gap being introduced and requiring an application to resubmit an old transaction.

**Comment by matthew1001** [comment]
I think this documentation topic is needed in order for candidates of the upcoming Besu certification to be able to answer some of the questions. Is it possible for it to be looked at in the near future?

**Comment by gtebrean** [comment]
@joaniefromtheblock could you please help us with it? We need this for the Besu certification sources.
