### ISSUE TITLE
Document how to use the cached genesis state.

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#1576]
Introduced a new CLI option.

Document `--use-cached-genesis-state-hash`. When this option is used to start the node, if the genesis state hash value is already stored in the database, the node will directly use this value (stored genesis state hash value) during startup.

For context, see: https://github.com/hyperledger/besu/pull/6758

**Comment by m4sterbunny** [comment]
PR in https://github.com/hyperledger/besu-docs/pull/1632
