### ISSUE TITLE
Document option to configure the price bump percentage required to replace blob transactions

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#1577]
Add `--tx-pool-blob-price-bump` option to configure the price bump percentage required to replace blob transactions (by default 100%), also a blob tx can only replace and be replaced by another blob tx.

See: https://github.com/hyperledger/besu/pull/6874

**Comment by m4sterbunny** [comment]
Bash: TX_POOL_BLOB_PRICE_BUMP
syntax: --tx-pool-blob-price-bump
