### ISSUE TITLE
Customized markdownlint style file required to override mdl --style all

### ISSUE THREAD

**Issue by grantnoble** [hyperledger/besu-docs#160]
To override the default rules provided by markdownlint we need a style file and update the `--style=all` option in the mdl command in circleci to use this new style.

https://consensys.slack.com/archives/GCEHWHAQ2/p1581509902077000

**Comment by NicolasMassart** [comment]
I will handle this plus a few other CI changes in the same PR as they are all about style checking and CI tools.
