### ISSUE TITLE
Add the Besu's Default configuration profile to the "Use a Profile" Page 

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu-docs#1611]
https://besu.hyperledger.org/24.5.0/public-networks/how-to/use-configuration-file/profile

The configuration page should enumerate the configuration for Besu's "default" i.e. no profile set. Users may be unaware of what is set by default, with or without a profile. It would be good to add it to this page (and/or one level up).

**Comment by m4sterbunny** [comment]
PR in BUT raised Qs for me>> https://github.com/hyperledger/besu-docs/pull/1631

**Comment by m4sterbunny** [comment]
Discussed with @non-fungible-nelson and the vision is to provide user deeper understanding of what the default config options provide.
Expanding issue to include this scope.

**Comment by m4sterbunny** [comment]
Matt is on holiday-- PR in waiting for his input https://github.com/hyperledger/besu-docs/pull/1644

**Comment by m4sterbunny** [comment]
Matt back from break -- asking him what content he wants to include to describe boilerplate config
