### ISSUE TITLE
Document the `eth_maxPriorityFeePerGas` API method

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#1618]
Document the  `eth_maxPriorityFeePerGas` API which returns an estimate of how much priority fee, in wei, you need to be included in a block.

See: https://github.com/hyperledger/besu/pull/7194

**Comment by m4sterbunny** [comment]
PR in for review> https://github.com/hyperledger/besu-docs/pull/1621#pullrequestreview-2134640142

**Comment by m4sterbunny** [comment]
Postman already out of date >> decision=no update
