### ISSUE TITLE
Document subnet-based peer permissions

### ISSUE THREAD

**Issue by joaniefromtheblock** [hyperledger/besu-docs#1625]
Document new feature for managing peer permissions based on IP subnet configurations in the networking layer

**Related to:** https://github.com/hyperledger/besu/pull/7168

**Comment by m4sterbunny** [comment]
todo: verify alphabetical order (!)
verify standards for array -- not consistent across cli options

**Comment by alexandratran** [comment]
Possibly add a section on this page: https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers

**Comment by m4sterbunny** [comment]
section added
