### ISSUE TITLE
WIP: Add experimental `--Xsnapsync-bft-enabled` option

### ISSUE THREAD

**Issue by joaniefromtheblock** [hyperledger/besu-docs#1626]
_This is still being developed. Check[ Eng PR](https://github.com/hyperledger/besu/pull/7140) to get status on feature_

* Update docs to reflect "how do the different sync modes work" and add private syncing to https://besu.hyperledger.org/development/public-networks/get-started/connect/sync-node

* Document `--Xsnapsync-bft-enabled` which enables snap sync for BFT chains.

**Related to**:  https://github.com/hyperledger/besu/pull/7140/commits

**Comment by alexandratran** [comment]
Note: We don't typically document experimental options in the CLI reference, but they can be mentioned in other parts of the docs.

**Comment by joaniefromtheblock** [comment]
Working on this. Need to get some more clarity from Eng. Will pick up next week.
