### ISSUE TITLE
Remove PKI backed QBFT docs

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1685]
PKI backed QBFT (block proposal permissioning) feature was removed from Besu https://github.com/hyperledger/besu/pull/7310

This page should be removed from docs -
https://besu.hyperledger.org/development/private-networks/how-to/configure/block-proposal-permissioning#xpki-block-creation-enabled

Also this section can be removed -
https://besu.hyperledger.org/development/private-networks/concepts/pki#block-proposal-permissioning

**Comment by Nimeshan** [comment]
Hi please check my Pull Request, I hope I have completed this as per your requirements. I would love to receive your feedback from your end.
