### ISSUE TITLE
Update documentation on minimum number of peers required before starting sync 

### ISSUE THREAD

**Issue by m4sterbunny** [hyperledger/besu-docs#1702]
Documentation required following update: default value for minimum number of peers required before starting sync (only used by non-PoS networks) from 5 to 1.
As per [this PR](https://github.com/hyperledger/besu/pull/7640): dependency, PR should be merged first

**Comment by macfarla** [comment]
@m4sterbunny @EstherLavender I'm closing this issue since we decided not to make this change.
