### ISSUE TITLE
bookmark to fast-sync-min-peers is outdated

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#1709]
The "danger" note here links to fast-sync-min-peers but the anchor has moved
https://besu.hyperledger.org/public-networks/reference/cli/options#remote-connections-limit-enabled

incorrect link
https://besu.hyperledger.org/public-networks/reference/cli/options#fast-sync-min-peers

Correct link
https://besu.hyperledger.org/public-networks/reference/cli/options#sync-min-peers-fast-sync-min-peers

**Comment by omahs** [comment]
@macfarla Hey, I just opened a PR for this and added a few typo fixes.
