### ISSUE TITLE
Warning needed on configuration starting a miner and opening RPC

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#207]
User feedback about configuration starting a miner and opening RPC.

https://besu.hyperledger.org/en/latest/HowTo/Get-Started/Starting-node/

> The configuration example on this page includes two things that seem ill-advised. There should, at least, be a warning to the user about (a) that this configuration starts a miner, and (b) that the RPC is 'wide open'. In the past, people said about both geth and parity that opening one's RPC in this way was asking for trouble. Maybe you shouldn't make that the default without at least a warning to the reader.

**Comment by grantnoble** [comment]
PR #228 fixes this issue. Closing.
