### ISSUE TITLE
More info required about limiting remote connections

### ISSUE THREAD

**Issue by grantnoble** [hyperledger/besu-docs#216]
In docs/HowTo/Find-and-Connect/Managing-Peers.md#limiting-remote-connections, more details required about why limiting remote connections is unnecessary. Perhaps when you should and when you should not limit remote connections.

**Comment by MadelineMurray** [comment]
Related conversation on RC - https://chat.hyperledger.org/channel/besu?msg=wBizpzyaeCFXbakfm
