### ISSUE TITLE
have you sharing some production adoption usecase for besu

### ISSUE THREAD

**Issue by xiaods** [hyperledger/besu-docs#225]
I am blockchain developer. I want to know the besu project if you have some production use case . thanks.

**Comment by faraggi** [comment]
Hi @xiaods ! Thanks for taking interest in Besu, the best place to ask this type of question is in our rocket chat.

Instructions for joining here: 
https://wiki.hyperledger.org/display/BESU/Rocket+Chat

This is our channel:
https://chat.hyperledger.org/channel/besu
