### ISSUE TITLE
Besu Wiki Article Explaining Release Philosophy

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#252]
We need a wiki article explaining our general release cadence philosophy, CI/CD driven numbering scheme, and rough guidance on quarterly big releases.

From Slack:
> i.e. our numbering is <milestone>.<quarterly>.<bi-weely>
> We bump milestone when a release is big enough (such as full mainnet compliance). We do a quarterly release where we upgrade all dependencies with a RC release, and bi-weekly all come in CD style. We don’t do multiple branches.

**Comment by macfarla** [comment]
How's this https://wiki.hyperledger.org/display/BESU/Release+Philosophy

**Comment by macfarla** [comment]
Added further info on numbering rationale

**Comment by MadelineMurray** [comment]
I think we probably need to explicitly state we're not using semantic versioning and mention that we do patch releases on a fortnightly cadence to allow access to bug fixes without delay.
