### ISSUE TITLE
Add Web3j Example to Besu docs

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#253]
The How To section currently has an example of creating a signed tx using Web3.js.

We should add a Web3j example as well.

**Comment by sambacha** [comment]
Can we expand the part of the documentation for just "Developer Resources"? For example, there is now a `svm` solidity version manager (like nvm/rvm) for web3j, https://github.com/web3j/svm

**Comment by MadelineMurray** [comment]
hi @sambacha - I'm actually closing this one.  We talked about it within the docs team and documenting products we don't maintain (eg, web3.js and web3j) in the Besu docs isn't really the right approach.  I think raising a docs issue on the Web3j docs probably makes sense here - https://github.com/web3j/web3j-docs
