### ISSUE TITLE
Confirm JavaDoc added for new BesuEvents

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#299]
PR: https://github.com/hyperledger/besu/pull/637 

Confirm PR merged before starting work. 

Events listed here 
https://javadoc.io/doc/org.hyperledger.besu/plugin-api/latest/org/hyperledger/besu/plugin/services/BesuEvents.html need to include new supported events.

**Comment by MadelineMurray** [comment]
PR now merged.

**Comment by grantnoble** [comment]
Besu [PR 728](https://github.com/hyperledger/besu/pull/728) created for this.
