### ISSUE TITLE
Update `gasUsed` description 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#302]
PR: https://github.com/hyperledger/besu/pull/592

Confirm PR merged before staring work. 

Current description: 
Gas used by the transaction. Includes any refunds of unused gas.

**Comment by grantnoble** [comment]
Reviewing this I don't think the description is "wrong". It could be updated to say it's calculated as `gasRemainingBeforeTransaction` minus `gasRemainingAfterTransaction` plus `unusedGas`, if that is what you are intending?

**Comment by MadelineMurray** [comment]
Following up with @matkt

**Comment by MadelineMurray** [comment]
Confirmed with @matkt current description is correct.
