### ISSUE TITLE
Make host-whitelist description clearer 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#309]
From https://github.com/hyperledger/besu/issues/615: 

> Unfortunately the documentation for the host-whitelist option is not completely clear. If you expose RPC services externally then you need to add the appropriate hostname or ip to the host-whitelist. By default a Besu node only allows JSON-RPC requests from localhost/127.0.0.1.

Note: Issue not yet resolved so may be more relevant information added.

**Comment by grantnoble** [comment]
Duplicate of issue #321 and fixed by PR #323. Suggest closing.

**Comment by bgravenorst** [comment]
I think this can be closed
