### ISSUE TITLE
Display the version number in the doc itself

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#340]
As feedback from a user on HotJar:

> https://besu.hyperledger.org/en/stable/
> The latest 'stable' version isn't indicated - it would be really helpful if this could be added!

It may help to have the version number displayed on the page and not only make the user able to deduce it from the highest version number in the popup box.

However this is a very hard one and no straightforward way to do it comes to my mind

**Comment by alexandratran** [comment]
Done in Docusaurus!
