### ISSUE TITLE
Documentation Error found on POA Speed section

### ISSUE THREAD

**Issue by yorkerhodes3** [hyperledger/besu-docs#353]
There is an editing error in the documentation ... here are some details:

At the Speed section of this link
https://besu.hyperledger.org/en/stable/Concepts/Consensus-Protocols/Comparing-PoA/

Clearly this needs to be edited: 
------
Speed
Reaching consensus and adding blocks is faster in Clique networks. For Clique, the probability of a fork increases number as the of validators increases.

For IBFT 2.0, the time to add new blocks increases as the number of validators increases.

failing or propagating incorrect information to peers.
-------

Suggested edit: 
-------
Speed
Reaching consensus and adding blocks is faster in Clique networks. For Clique, the probability of a fork increases as the number of validators increases.

For IBFT 2.0, the time to add new blocks increases as the number of validators increases.
--------

**Comment by MadelineMurray** [comment]
@yorkerhodes3 - thanks for taking the time to raise.  Have fixed this now and it will be available in Thursday's release or on latest https://besu.hyperledger.org/en/latest/Concepts/Consensus-Protocols/Comparing-PoA/
