### ISSUE TITLE
Add section on Azure Cloud Deployment

### ISSUE THREAD

**Issue by yorkerhodes3** [hyperledger/besu-docs#354]
It would be great to add a section in the docs referring to the Azure Cloud deployment now available from the Azure Marketplace 

https://azuremarketplace.microsoft.com/en-us/marketplace/apps/consensys.hyperledger-besu-quickstart?tab=Overview

A simple walkthrough of what is required to do that deployment with steps and screen shots 
Prerequirements: 
- Azure Account ... it is possible you could do this on a free Azure account as well, which might be interesting to point out 

Navigate to Azure Marketplace: 
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/consensys.hyperledger-besu-quickstart?tab=Overview

Click ...

**Comment by bgravenorst** [comment]
Already been documented here: https://besu.hyperledger.org/en/latest/Tutorials/Examples/Private-Network-Example-Azure/

See: https://github.com/hyperledger/besu-docs/pull/357
