### ISSUE TITLE
Consistency on JVM and VM memory pre-requisites

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#355]
Feedback from a user on HotJar:
On https://besu.hyperledger.org/en/stable/HowTo/Get-Started/System-Requirements/
> If the JVM is recommended to be 4 to 8 GB by itself, then it doesn't make sense to recommend that a VM be created with 4 GB, since it has to fit both the OS + the JVM.

**Comment by alexandratran** [comment]
This appears no longer an issue: https://besu.hyperledger.org/en/stable/HowTo/Get-Started/System-Requirements/System-Requirements-Private/

**Comment by NicolasMassart** [comment]
Not sure as this page still displays :
> Java Virtual Machine size
Depending on your environment and network setup, the minimum Java Virtual Machine (JVM) memory requirement for private networks is 4GB.

and 

> VM requirements
Memory Size: Set to 4096 MB (recommended)

Which is also 4Gb (==4096 MB).

(by the way, using consistent units would be nice, either Gb or Mb but not both for the same value on the same page. Consistency across all the doc would be a plus)
