### ISSUE TITLE
Use web3js and eth-crypto instead of ethereumjs-tx

### ISSUE THREAD

**Issue by yehia67** [hyperledger/besu-docs#369]
Hello,
I was trying to deploy a smart contract using code only. So I decided to make a raw transaction in order to deploy the smart contract by following this [tutorial](https://besu.hyperledger.org/en/1.2.0/Using-Pantheon/Transactions/Transactions/) 
The included code has some mistakes like
1-     `const ethTx = require('ethereumjs-tx')` this line cause error ` ethTx is not a constructor` in order to solve it you need to `const ethTx =require('ethereum-tx').Transaction` referring to this [issue](https://github.com/ethereumjs/ethereumjs-tx/issues/160)

2- After updating the package the code will run but will output this error.  `Invalid JSON RPC response `  I don't know why but ` ethereumjs-tx ` packages don't work. 

You can find the code here

https://besu.hyperledger.org/en/1.2.0/Using-Pantheon/Transactions/scripts/create_value_raw_transaction.js

https://besu.hyperledger.org/en/1.2.0/Using-Pantheon/Transactions/scripts/create_contract_raw_transaction.js

All you need to do is instead of signing the transaction using etherumjs-tx and hard code the contract data you could make something like that.

```
const EthCrypto = require('eth-crypto');
 const bytecode = contractArtifacts.bytecode.substring(2); //remove 0x from data
    const contractData = EthCrypto.txDataByCompiled(
      contractArtifacts.abi, // abi
      bytecode, // bytecode
      args // constructor-arguments
  );
```
Then sign and send data using web3js
```
 const signed = await web3.eth.accounts.signTransaction({
    from:addressFrom,
    data: contractData,
    gasPrice: 0,
    gas:'0x1ffffffffffffe' ,
    nonce: await web3.eth.getTransactionCount(addressFrom, 'pending')
  }, private_key);
  const receipt = await web3.eth.sendSignedTransaction(signed.rawTransaction);
```

**Comment by MadelineMurray** [comment]
Thanks for taking the time to raise this @yehia67.  I'm going to convert this to a docs issue in the besu-docs repo so we can address it.
