### ISSUE TITLE
Recommended JVM memory values?

### ISSUE THREAD

**Issue by hmijail** [hyperledger/besu-docs#371]
The recommended value is 8GB for mainnet. But then we're told that 2 values can be provided to the JVM. How does the 8GB translate into the Xmx and Xms values? What is the recommendation?

https://besu.hyperledger.org/en/stable/HowTo/Get-Started/System-Requirements/

**Comment by MadelineMurray** [comment]
The references to Xmx and Xms have now been removed so closing this one.
