### ISSUE TITLE
The Postman json file has wrong chars

### ISSUE THREAD

**Issue by hmijail** [hyperledger/besu-docs#381]
File https://besu.hyperledger.org/postman/92e3da11d1769ce7e667.json, linked at https://besu.hyperledger.org/en/stable/Reference/API-Methods/ 

Example: "eth_getProof" has an extraneous "\u202d" in rawModeData which confuses Postman (the text cursor inserts text one char away from where it appears) and sends wrong queries to Besu, who answers with error messages.

**Comment by hmijail** [comment]
Searching for "\u" shows more possibly wrong chars.

**Comment by NicolasMassart** [comment]
Could you tell me if this version of the file (exported in latest Postman format and I don't see any strange unicode chars) is working for you please?
[Hyperledger Besu JSON-RPC APIs.postman_collection.json.zip](https://github.com/hyperledger/besu-docs/files/4682160/Hyperledger.Besu.JSON-RPC.APIs.postman_collection.json.zip)

**Comment by hmijail** [comment]
The problem is only visible when you try to use the affected API, so I can't confirm. If I find any during my use I'll notify.

**Comment by NicolasMassart** [comment]
Can you try to do what you did when you found the bug? Not testing the fix on your side is not going to help me solve this issue as I don't have the issue myself. I can still update the file in case of and because having the latest format is nice, but I can't guarantee that it solves you problem and then can't honestly close this issue.

**Comment by hmijail** [comment]
It's the first time I have this kind of response when reporting bugs to either open or closed source software.
I am no longer using Postman nor Besu so let me know if I should close this myself.
