### ISSUE TITLE
Broken internal links on Create IBFT Network page

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#418]
## Describe the bug

Broken internal links
at top of page I think the [IBFT...] is meant to be a link? but is showing with the square brackets
A private network provides a configurable network for testing. This private network uses the [IBFT 2.0 (Proof of Authority) consensus protocol].

step 6 at end of page
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#6-start-first-node-as-bootnode

and step 3 in this note 
To add or remove nodes as validators you need the node address. The directory created for each node has the node address as the name.
links to 
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#3-generate-node-keys-and-genesis-file
instead of 
https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/#3-generate-node-keys-and-a-genesis-file

Check the issue type in the following list (insert X instead of space between [ ]): -->

- [ ] Missing content
- [x ] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

## Change suggestion

link to step 6 is broken because wording has changed - is there a way to avoid this?

**Comment by sambacha** [comment]
These were recently updated actually, two days ago in fact.

See commit: #404 

https://github.com/hyperledger/besu-docs/commit/489395da73ee536cf8256da49746d0994ba760a5

Directory of relevant information: 
https://github.com/hyperledger/besu-docs/tree/master/docs/HowTo/Configure

Alt. try and visit this: 
https://besu.hyperledger.org/en/latest/Tutorials/Private-Network/Create-IBFT-Network/#3-generate-node-keys-and-a-genesis-file

Changes `stable` to `latest`

**Comment by MadelineMurray** [comment]
Fixed in https://github.com/hyperledger/besu-docs/pull/584

**Comment by MadelineMurray** [comment]
Raised https://github.com/ConsenSys/protocol-misc/issues/236 to investigate adding a check for this generally.
