### ISSUE TITLE
Update debug_traceTransaction example

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#433]
PR: https://github.com/hyperledger/besu/issues/1066

**Comment by timbeiko** [comment]
@MadelineMurray our current docs don't show either the old or new version for brevity, which seems okay. `stack` and `memory`, the two field whose return values were changed, are just shown as arrays. 

<img width="772" alt="Screen Shot 2020-09-08 at 2 46 22 PM" src="https://user-images.githubusercontent.com/9390255/92530882-14145080-f1e2-11ea-818d-f0e5d477b631.png">

I think we can close this.
