### ISSUE TITLE
Standardise on quotes or no quotes for boolean values in config files 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#434]
PR: https://github.com/hyperledger/besu/pull/1065

**Comment by timbeiko** [comment]
This PR (https://github.com/hyperledger/besu-docs/pull/511) addresses the Besu bit of it.

**Comment by timbeiko** [comment]
This commit (https://github.com/PegaSysEng/doc.plus/commit/da2638dba424a1f74f42598698ac00cf7ca0550e) addresses the Quorum Plugin repo bit of it. Once the above PR is merged, this can be closed.
