### ISSUE TITLE
Doc how to configure configurable block rewards and recipients for IBFT 2.0 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#436]
PR: https://github.com/hyperledger/besu/pull/1132

**Comment by bgravenorst** [comment]
I documented the `blockreward` and `miningbeneficiary` IBFT properties here:

https://github.com/hyperledger/besu-docs/commit/1ad4b9a76177c07219ce01adf84c8050438a15e5

**Comment by eum602** [comment]
I think I would be great if the block reward were configurable even after the network is started. Is it feasible?
