### ISSUE TITLE
Impact of on-chain privacy groups on privacy marker transaction

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu-docs#438]
## Describe the bug

On-chain privacy groups adds an additional privacy precompile address, but the documentation makes no mention of this. This can lead to confusion when users try to use on-chain privacy groups and manually generate privacy marker transactions. 

Check the issue type in the following list:

- [x] Missing content
- [x] Outdated content
- [ ] Wrong content
- [x] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/latest/Concepts/Privacy/Private-Transaction-Processing/

https://besu.hyperledger.org/en/latest/HowTo/Send-Transactions/Concurrent-Private-Transactions/

## Change suggestion

For the first page -> Adding a info/warning pane detailing the different precompiles

For the second page -> Clarify the example is for off-chain privacy groups

## Screenshots

N/A

**Comment by MadelineMurray** [comment]
hi @magooster - this PR makes the changes you identified above:  
https://github.com/hyperledger/besu-docs/pull/477

This is another one making changes also around the privacy precompile address: 
https://github.com/hyperledger/besu-docs/pull/468 

Thanks for taking the time to raise this :-)
