### ISSUE TITLE
Add Blockscout as a Besu Compatible Block Explorer 

### ISSUE THREAD

**Issue by sambacha** [hyperledger/besu-docs#440]
## Describe the bug

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [x] Other

## Additional Content

Add Blockscout to supported Block Explorers 

https://github.com/poanetwork/blockscout/tree/besu-revert-reason
https://github.com/poanetwork/blockscout/pull/3182
https://forum.poa.network/t/besu-ethereum-jsonrpc-variant-dont-show-blocks-and-transactions/3556/6
## Change suggestion

Add Blockscout as a Besu compatible Block Explorer 

## More context

[Blockcscout](https://github.com/poanetwork/blockscout/tree/master) is a Blockchain explorer for Ethereum based network and a tool for inspecting and analyzing EVM based blockchains.

## Additional Notes

[Blockscout is Licensed under GPLv3](https://github.com/poanetwork/blockscout/blob/master/LICENSE)

**Comment by MadelineMurray** [comment]
Add a 'projects using Besu' page in resources and include there.

**Comment by MadelineMurray** [comment]
@sambacha - thanks for raising this and I've added this to the docs backlog.
