### ISSUE TITLE
Doc parity compatible pendingTransactions API

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#442]
See: https://github.com/hyperledger/besu/issues/1126

Check PR merged before doc'ing

**Comment by timbeiko** [comment]
Can you assign this to me @bgravenorst @NicolasMassart ? Going to try and take a stab at it 😅

**Comment by timbeiko** [comment]
This seems to have been done, see https://besu.hyperledger.org/en/latest/Reference/API-Methods/#txpool_besupendingtransactions
