### ISSUE TITLE
RSS Feeds for Besu Updates

### ISSUE THREAD

**Issue by sambacha** [hyperledger/besu-docs#447]
# RSS feeds for updates 
Trying to keep up with updates can be tiresome, so if anyone wants RSS feeds here are two:

### hyperledger/besu master branch commits as an RSS feed
https://github.com/hyperledger/besu/commits/master.atom

&& 

### docker container updates as an RSS feed
https://docker-hub-rss.now.sh/hyperledger/besu.atom

**Comment by MadelineMurray** [comment]
Thanks @sambacha - we'll add this to the changelog and wiki.

**Comment by sambacha** [comment]
Also, I always forget there is an official Wiki, I can't remember seeing it in the offical docs, is that still a valid source?

Thanks.

**Comment by alexandratran** [comment]
Added here: https://wiki.hyperledger.org/display/BESU/Repositories+and+other+projects
