### ISSUE TITLE
search for "sendrawtransaction" doesn't return all results

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu-docs#448]
## Describe the bug

The 2 results returned are both for eea_sendRawTransaction. The pages with eth_sendRawTransaction (eg https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_sendrawtransaction) do not appear in search results.

Check the issue type in the following list (insert X instead of space between [ ]): -->

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [x] Other

## The broken page
Could be an issue with indexing this page:
https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_sendrawtransaction

**Comment by NicolasMassart** [comment]
See if material design theme update fixes this
