### ISSUE TITLE
Update permissioning endpoint names to allowlist

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#457]
Update permissioning endpoint names to allowlist
PR: https://github.com/hyperledger/besu/pull/1094
PR: https://github.com/hyperledger/besu/pull/1095

**Comment by timbeiko** [comment]
@MadelineMurray pretty sure that @bgravenorst has already gotten to this. There aren't any instances of `whitelist` anywhere except within the [postman file](https://github.com/hyperledger/besu-docs/blob/master/docs/postman/e8934bc8b98d8c036254.json). Should we update that too?

**Comment by MadelineMurray** [comment]
Great.  Yes we probably should update the Postman file.

**Comment by timbeiko** [comment]
Postman is done, see PR above. This ticket can be closed @MadelineMurray
