### ISSUE TITLE
Doc eth_batchSendRawTransaction

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#474]
PR: https://github.com/hyperledger/besu/issues/1350 (check merged first) 

This issue is to doc eth_batchSendRawTransaction only not EIP 1559 generally.

**Comment by timbeiko** [comment]
FYI this API should end up being in its own PR vs. the 1559 one: https://github.com/hyperledger/besu/pull/1281#issuecomment-671482852

**Comment by MadelineMurray** [comment]
Updated description to reference PR for `eth_batchSendRawTransaction` specifically
