### ISSUE TITLE
Add link to the services method to explain where RPC is advertised when setting NAT

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#515]
## Describe the bug

I had a report from a user saying:

> It doesn't make sense that rpc-http-* are advertised, nor that they are ignored if NAT=NONE. In principle they shouldn't be affected by NAT at all. Are you sure?

It doesn't seem clear why RPC address is advertised and where.

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [x] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Specifying-NAT/#none 

## Change suggestion

RPC are advertised in the services RPC method and it may help to have a sentence with a link to https://besu.hyperledger.org/en/stable/Reference/API-Methods/#net_services to explain this.

## More context

Feedback from HotJar user

**Comment by alexandratran** [comment]
Metrics were also added to the services RPC method since this issue was opened, so they also need to be added as options when NAT=NONE.

**Comment by NicolasMassart** [comment]
Sorry it seems metrics was already in eth_services, but then it means we missed this when documenting nats part...
@matkt could you confirm that please?

**Comment by matkt** [comment]
> Sorry it seems metrics was already in eth_services, but then it means we missed this when documenting the NAT part...
> @matkt could you confirm that please?

Metrics is not linked to NATS at this time. You can have the list in this link

https://github.com/hyperledger/besu/blob/8b6f8b6e2f8f498af71523580eb0d6e6779d06c7/nat/src/main/java/org/hyperledger/besu/nat/core/domain/NatServiceType.java#L29

**Comment by NicolasMassart** [comment]
Thanks @matkt , so it means that metrics host and port values in the `eth_services` method response are only defined by the command line options `--metrics-host` and `--metrics-port` or their default values.
Maybe it then require the changes to cover the NAT doc for  json-rpc and p2p (rlpx and discovery) but also add some explanation of what values are impacted by NAT setting in `eth_services`: json-rpc, p2p but not metrics.
