### ISSUE TITLE
Remove Metamask links for excluded list 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#537]
I added the following links to the ignore list because they were failing the link checker but are not broken: 
```
{
            "pattern": "https://metamask.zendesk.com/hc/en-us/articles/360015489331-Importing-an-Account-New-UI-"
        },
        {
            "pattern": "https://metamask.zendesk.com/hc/en-us/articles/360015289452-Creating-Additional-MetaMask-Wallets-New-UI-"
        },
        {
            "pattern": "https://metamask.zendesk.com/hc/en-us/articles/360015488991-Sending-Ether-New-UI-"
        }, 
```

Need to investigate why they are causing the link checker to fail currently, fix, and then remove from ignore list.

**Comment by NicolasMassart** [comment]
I have to update the link checker on Besu (I did it on all other sites but Besu is not Consensys so not linked to the common repos). I think it should fix the issue.

**Comment by NicolasMassart** [comment]
But not only. Zendesk is protected by CloudFlare, as is Consensys website. CF issues a challenge (Captcha) to the user to make sure that it's not a bot. Our Link checker is indeed a bot, a nice one, but still a bot... so we can't access the pages on this domains. As I guess there will be more and more sites doing this, we will either need to ask each of them to ass our CI IP to their rules (good luck) or stop checking them.
I sadly think we don't have the choice and we need to exclude these sites when we find one.

**Comment by NicolasMassart** [comment]
See tcort/markdown-link-check#109
