### ISSUE TITLE
Add troubleshooting info on fast sync 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#546]
From this thread: https://discord.com/channels/697535391594446898/743193040197386451/777730977065730058

The Pending State Nodes count is the number of nodes that yet have to be downloaded and it should change constantly.  Pending State Nodes trends to 0 during fast sync and then goes to 0. 

The issue the Pivot Block of 0 - this indicates your node isn't syncing against any peers but once was (that's where the pending nodes came from).

Fast sync is likely to reset once a new pivot block is added so the easiest course of action at this point, is probably to start over.

**Comment by bgravenorst** [comment]
Currently the Syncing options content is in the Pruning topic.

We need to move the syncing (currently Archive and Fast sync) to it's own topic and provide more conceptual information. For example, what is the pivot block number, and how does Besu use this. By adding enough conceptual info we can also cover this issue.
