### ISSUE TITLE
Port number '8546' has been specified multiple times.

### ISSUE THREAD

**Issue by opentaps** [hyperledger/besu-docs#547]
## Describe the bug

Using besu/v20.10.0/osx-x86_64/oracle-java-11, I got error Port number '8546' has been specified multiple times.

I changed Node-2, -3, and -4 to 8646, 8647, and 8648 and was able to get it to work.

Check the issue type in the following list (insert X instead of space between [ ]): -->

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [ X ] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/

## Change suggestion

Change the port numbers?

**Comment by MadelineMurray** [comment]
hi - thanks for taking the time to raise. 

On the stable version of the docs the commands have different port numbers: 
Node 1 - `besu --data-path=data --genesis-file=../genesis.json --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all"`
Node 2 - `besu --data-path=data --genesis-file=../genesis.json --bootnodes=<Node-1 Enode URL> --p2p-port=30304 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8546`
Node 3 - `besu --data-path=data --genesis-file=../genesis.json --bootnodes=<Node-1 Enode URL> --p2p-port=30305 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8547`
Node 4 - `besu --data-path=data --genesis-file=../genesis.json --bootnodes=<Node-1 Enode URL> --p2p-port=30306 --rpc-http-enabled --rpc-http-api=ETH,NET,IBFT --host-allowlist="*" --rpc-http-cors-origins="all" --rpc-http-port=8548`

Did you copy and paste these commands?

**Comment by opentaps** [comment]
Yes, I did.  The problem was it didn't like using port 8546 on Node 2
because it had been used already.  So I had to change the ports to 8646,
8647, and 8648 to get it to work.
-----
Si Chen
Open Source Strategies, Inc.

Video: Fighting Climate Change with Blockchain and Open Source
<https://youtu.be/NgxNWXa_IjE>

**Comment by MadelineMurray** [comment]
Resolved by this Besu change - https://github.com/hyperledger/besu/pull/1673
