### ISSUE TITLE
Add batch request support doc

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#559]
## Describe the bug

- Doc doesn't explain how to send http or ws batch requests

This is related to hyperledger/besu#1583

- [x] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## The broken page

[Paste the doc site page link here.]

Not sure if it should be in `/Reference/API-Methods/` or `/HowTo/Interact/APIs/Using-JSON-RPC-API/`

## Change suggestion

Add at least a `!!!tip` block on the fact that we can send more than one request by HTTP/WS command.

**Comment by macfarla** [comment]
Basically the request can be an array of JSON-RPC objects
eg on WS
```
wscat -c ws://localhost:8546
Connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}
< {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"}
> [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_peers","params":[]}]
< [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"},{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":[]}]
>  [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_sdfpeers","params":[]}]
< [{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x23"},{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","error":{"code":-32601,"message":"Method not found"}}]
```
^ 
1. single request (eth_blockNumber)
2. batch of 2 requests (eth_blockNumber, admin_peers)
3. batch of 2 requests(eth_blockNumber, nonexistent_method)
If Request is an array, Response is an array

It's the same over HTTP. You can send this via Postman
`[{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_peers","params":[]}]`

or use curl
```
curl -X POST --data '[{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"eth_blockNumber","params":[]}, {"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","method":"admin_peers","params":[]}]' http://127.0.0.1:8555
```
In both cases the response is the same ie an array:
`[{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":"0x60e"},{"jsonrpc":"2.0","id":"8ab22d47-5002-433f-b921-00f7e339f72d","result":[]}]`
