### ISSUE TITLE
Update Postman online collection

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#561]
HL team is being configured.
TODO:
- [ ] finish to configure HLF team (Ry Jones)
- [x] migrate collection to new team
- [x] update doc with new links (see PR #603)
- [ ] update collection with missing methods
- [ ] add doc for each method (copy paste MD from doc)
- [ ] publish doc once team is setup
- [ ] update links to Postman collection in 
  - https://besu.hyperledger.org/en/stable/Reference/API-Methods/
  - https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Using-JSON-RPC-API/
- [ ] add link to the postman public doc and HL workspace

**Comment by bgravenorst** [comment]
According to user feedback, we should also consider making the Postman collection a bit more obvious. 

Maybe upfront in this [topic](https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Using-JSON-RPC-API/) we should discuss using curl or Postman.

Also, another suggestion was to add content to the [Private Network](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-Private-Clique-Network/#next-steps) section.

**Comment by NicolasMassart** [comment]
Awaiting for ans answer about the Postman Hyperledger Group as I think we should publish the collection under this group.

**Comment by NicolasMassart** [comment]
HL team is being configured.
TODO:
- [ ] finish to configure HLF team (Ry Jones)
- [x] migrate collection to new team
- [x] update doc with new links (see PR #603)
- [ ] publish doc once team is setup

**Comment by NicolasMassart** [comment]
RJ is having some issues making Postman support recover the HL domain and assign it to the team. WIP...
