### ISSUE TITLE
Lack Of Documentation / Example About Peer Discovery Options

### ISSUE THREAD

**Issue by urtuba** [hyperledger/besu-docs#568]
## Describe the bug

I am new to Hyperledger Besu and blockchain development, I created many network working locally or with dockers without problems. I am trying to run basic IBFT 2.0 network (in tutorials) in Google Cloud. I created 4 compute engines and started nodes from each other. I tried a lot of cloud configuration and host specification but my nodes do not discover each other.

Since all the examples about private networks run in local environment, there is no useful guide to deploy it to cloud. Options section of documentation has superficial information. I could not reach any good resource to start nodes in separate computers/cloud machines. I don't know how to configure p2p and rpc-http stuff. It can be beneficial if it is supported by better documentation or an example.

- [x] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [x] Confusing or misleading content
- [ ] Other

## The broken page

[Deploy to cloud documentation, there is no technical details or examples](https://besu.hyperledger.org/en/stable/HowTo/Deploy/Cloud/)
[Private network documentation in local, it is perfect](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/)
[Command line options, they are not obvious to chose right ones for beginners](https://besu.hyperledger.org/en/stable/Reference/CLI/CLI-Syntax/)

## Change suggestion

You could give guide and examples about configurations in distributed private networks. Especially in the peer  discovery subject.

**Comment by MadelineMurray** [comment]
@urtuba - thanks for taking the time to raise. 

We also have this page about configuring ports for access - https://besu.hyperledger.org/en/stable/HowTo/Find-and-Connect/Configuring-Ports/ 

Would adding an example for Google Cloud help?
