### ISSUE TITLE
Make clear that disabling and then re-enabling account permissioning will result in invalid blocks

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu-docs#610]
If account permissioning is enabled for a node, all transactions need to be allowed as per the permissioning contract at the chain height of the transaction.  That is, if transactions are added to the chain while account permissioning is turned off and account permissioning is later re-enabled, nodes will not be able to resync the network

**Comment by bgravenorst** [comment]
This isn’t a problem for local permissioning because we don’t validate local account permissioning when importing blocks.
