### ISSUE TITLE
Describe how to send multiple private txs in sequence

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#703]
Sending multiple private txs in sequence requires the user to manage the nonce themselves. Usually, they will create the Privacy Market Transaction themselves instead of letting Besu do it.

It might be worth considering adding a section that explain the process of sending private txs using (priv_distributeRawTransaction and eth_sendRawTransaction).

For context, see: https://github.com/hyperledger/besu-docs/pull/699

**Comment by alexandratran** [comment]
Added private nonce management content in #890.
