### ISSUE TITLE
Document GoQuorum privacy mode

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#709]

**Comment by vmichalik** [comment]
Dev PRs:
hyperledger/besu#1859
hyperledger/besu#1872

**Comment by vmichalik** [comment]
Putting up a single page to allow people to enable this mode and use it should be prioritized as an MVP
The page should contain
- How to set up and configure the single private state mode
- Links to relevant GoQuorum private transaction docs
- Contact us on Rocket Chat if you’re planning to use the mode

**Comment by vmichalik** [comment]
Once this is in place we can add something like this note to the Besu changelog:
This release adds a new, additional privacy mode: restricted privacy with a single private state. This privacy mode uses Tessera and is interoperable with GoQuorum. Find more information here: [docs link]
