### ISSUE TITLE
Replace web3js-eea references with web3js-quorum

### ISSUE THREAD

**Issue by vmichalik** [hyperledger/besu-docs#743]
## Describe the bug

Web3js-eea is being deprecated and replaced with web3js-quorum
Several docs pages are impacted by this change

Check the issue type in the following list (insert X instead of space between [ ]): -->

- [ ] Missing content
- [X] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/stable/HowTo/Interact/Client-Libraries/web3js-eea/
https://besu.hyperledger.org/en/stable/Tutorials/Privacy/web3js-eea-Multinode-example/
https://besu.hyperledger.org/en/stable/Tutorials/Examples/Privacy-Example/
https://besu.hyperledger.org/en/stable/HowTo/Develop-Dapps/Client-Libraries/
https://besu.hyperledger.org/en/stable/HowTo/Send-Transactions/Concurrent-Private-Transactions/
https://besu.hyperledger.org/en/stable/Concepts/Privacy/Flexible-PrivacyGroups/
https://besu.hyperledger.org/en/stable/HowTo/Send-Transactions/Creating-Sending-Private-Transactions/
https://besu.hyperledger.org/en/stable/Concepts/Privacy/Private-Transactions/

## Change suggestion

Replace web3js-eea with web3js-quorum on the affected pages

**Comment by bgravenorst** [comment]
Implemented these changes in https://github.com/hyperledger/besu-docs/pull/779/files
