### ISSUE TITLE
Link to Rocket Chat in "How to Contribute" Article

### ISSUE THREAD

**Issue by t-proctor** [hyperledger/besu-docs#755]
## Describe the bug
The "How to Contribute" page mentions, "Our Rocket Chat also requires a Linux Foundation (LF) account.". However, the Rocket Chat is not linked (although it is in the side dropdown).

- [ ] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [X] Confusing or misleading content
- [ ] Other

## The broken page

[https://wiki.hyperledger.org/display/BESU/How+to+Contribute](https://wiki.hyperledger.org/display/BESU/How+to+Contribute)

## Change suggestion

Linking to the [Rocket League doc page](https://wiki.hyperledger.org/display/BESU/Rocket+Chat) will save users time and confusion. This will read as "Our [Rocket Chat](https://wiki.hyperledger.org/display/BESU/Rocket+Chat) also requires a Linux Foundation (LF) account."

**Comment by rolandtyler** [comment]
Updated the [page](https://wiki.hyperledger.org/display/BESU/How+to+Contribute) per the above. @alexandratran, could you close this issue for me, since I'm still not a maintainer?
