### ISSUE TITLE
Add more info and boilerplate code to the contract deployment doc

### ISSUE THREAD

**Issue by NicolasMassart** [hyperledger/besu-docs#758]
Hotjar user feedback on https://besu.hyperledger.org/en/stable/Tutorials/Contracts/Deploying-Contracts/

> Great information overall but it lacks a bit of information & boilerplate code (ready-to-use) within this "Deploy a Contract" section: some further information is available on the GitHub repo but using a different host (through ethsignerProxy) while it is not mentioned here. Makes it a bit confusing to understand exactly how to deploy a contract :/

![image.png](https://images.zenhubusercontent.com/5bfbb441bde2e4315fb0087a/dfa12919-2aae-46b9-bb98-33af6b0b0593)

**Comment by alexandratran** [comment]
This seems to be a duplicate of issue #760, which was recently fixed in #880
