### ISSUE TITLE
Correct detail on JDK support

### ISSUE THREAD

**Issue by vmichalik** [hyperledger/besu-docs#771]
Currently Besu does not support JDK 17, so the statement that JDK 11+ are supported is not true. This may require further investigation. See hyperledger/besu#2617

**Comment by vmichalik** [comment]
In particular, errors are caused by trying to use Java 17 ->

https://docs.gradle.org/current/userguide/compatibility.html
A Java version between 8 and 16 is required to execute Gradle. Java 17 and later versions are not yet supported.

**Comment by alexandratran** [comment]
From Adrian: "It’s important to note the differences in requirements for running besu (11+ including 16 and 17 early access builds) and compiling besu (11-15 in current release, 11-16 in develop).  Most users only need to care about running besu so any Java from 11 up is fine."

Using a table might help.

**Comment by atoulme** [comment]
We can target Java 11 for compilation. I have seen this fail when we rely on classes that only exist in later versions of Java. This tends to become a problem when we detect that late in development, but I guess we can live with that for a couple major releases.
