### ISSUE TITLE
QBFT Consensus Algorithm Documentation

### ISSUE THREAD

**Issue by cyrilnavessamuel** [hyperledger/besu-docs#788]
Hello Team,

I dont think this would qualify as an issue but this is a more general request. Please excuse.

I would like to know if there would be any documentation or a paper describing your proposed QBFT consensus algorithm.

Please would like to also know the differences at algorithm level between IBFT2.0 and QBFT although I have seen your documentation on comparison of different PoA algorithms.

Thanks for your help,
Cyril

**Comment by cyrilnavessamuel** [comment]
Hi Team,
I would like to extend and test on Besu library my own consensus algorithm more like a randomised BFT as part of my doctoral work, I would like to know if there's any documentation I could follow on how to start my development and the architecture of Besu, please. Thanks

**Comment by rolandtyler** [comment]
Consensus descriptions updated in #965. Algorithm specific content outside the scope of these documents.
