### ISSUE TITLE
Update Quickstart to indicate that the M1 processor is not yet supported

### ISSUE THREAD

**Issue by bgravenorst** [hyperledger/besu-docs#898]
Add info about the M1 chip [here](https://besu.hyperledger.org/en/stable/Tutorials/Examples/Private-Network-Example/#prerequisites).

also it might be good to add something in the troubleshooting section - it looks like it all starts up ok but symptoms are

- all RPC calls (via curl or postman) return Empty reply from server
- grafana dashboard shows no data
- docker ps shows the containers running but with AMD warning about degraded performance
- no logs can be loaded in docker desktop

AMD warning is "Image may have poor performance, or fail, if run via emulation"

**Comment by macfarla** [comment]
WIP PR to add support for M1 compatible docker images https://github.com/hyperledger/besu/pull/2954
