### ISSUE TITLE
Document Besu behaviour when syncing with mainnet

### ISSUE THREAD

**Issue by frankisawesome** [hyperledger/besu-docs#906]
## Describe the bug

- [x] Missing content
- [ ] Outdated content
- [ ] Wrong content
- [ ] Confusing or misleading content
- [ ] Other

## The broken page

https://besu.hyperledger.org/en/stable/Concepts/Node-Types/#run-a-full-node

We should document the sync behaviour when Besu enters world state download phase more, so users don't get confused by the low activity level.

https://github.com/hyperledger/besu/issues/2753

**Comment by rolandtyler** [comment]
[Page ](https://besu.hyperledger.org/en/stable/Concepts/Node-Types/#run-a-full-node)has note advising of low activity and the length of time needed for sync.
